name: CI
on:
  push:
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Install graphviz
        run: sudo apt install graphviz
      - run: |
          java --version
          dot -V
      - name: Build & Deploy to GitHub Pages
        uses: MarkBind/markbind-action@release/v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      

