name: CI
on:
  push:
jobs:
  test:
    strategy:
      matrix:
        platform: [macOS-latest]
    runs-on: ${{ matrix.platform }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Graphviz
        uses: tlylt/install-graphviz@main
      # - uses: actions/setup-java@v3
      #   with:
      #     java-version: '11'
      #     distribution: 'temurin'
      # - name: Install graphviz
      #   run: sudo apt install graphviz
      # - run: |
      #     java --version
      #     dot -V
      - run: npm i -g markbind-cli
      - run: markbind build
      - name: Upload artifacts 
        uses: actions/upload-artifact@v2
        with:
          name: markbind-deployment
          path: |
            ./_site